In [1]:
import cv2
import argparse
import csv
import math
import pickle
import numpy as np
import random
import os
import sys

In [2]:
import os
print("Current working directory:", os.getcwd())

Current working directory: c:\Users\kangb3\Desktop\GT\ME7785Lab\Lab6_ws


In [28]:
data_path = "./pics2/"
data_split_ratio = "0.8"
knn_value = "5"
image_type = ".png"
save_flag = "-s"

!python ./example_knn1.py -p {data_path} -r {data_split_ratio} -k {knn_value} -i {image_type} {save_flag}


True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [29]:
# Define the paths relative to the current working directory.
data_path = "./pic/"         # Path to validation dataset folder
model_path = "./knn_model.xml"         # Path to your saved model file

# Run the model grader script
!python ./model_grader.py --data_path {data_path} --model_path {model_path}

Image: ts1.png - True: 5, Predicted: 1
Image: ts2.png - True: 5, Predicted: 5
Image: ts3.png - True: 5, Predicted: 5
True
Image: ts4.png - True: 1, Predicted: 1
True
Image: ts5.png - True: 2, Predicted: 2
Image: ts6.png - True: 4, Predicted: 4
True
Image: ts7.png - True: 1, Predicted: 1
Image: ts8.png - True: 3, Predicted: 3
Image: ts9.png - True: 3, Predicted: 3
Image: ts10.png - True: 4, Predicted: 4
True
Image: ts11.png - True: 1, Predicted: 1
True
Image: ts12.png - True: 2, Predicted: 2
True
Image: ts13.png - True: 2, Predicted: 2
True
Image: ts14.png - True: 1, Predicted: 1
True
Image: ts15.png - True: 2, Predicted: 2

Total accuracy: 0.9333333333333333
Confusion Matrix:
[[0 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 2 0]
 [0 1 0 0 0 2]]
